app:
  id: skycloud-base-monitor
apollo:
  custom:
    dev:
      meta: http://127.0.0.1:8081
    fat:
      meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
